name: Build Vagrant Box

on:
  push:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'
      - 'cookbooks/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKER_VERSION: "1.9.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install VirtualBox
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox

      - name: Install Vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant
          vagrant --version

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Initialize Packer
        run: packer init packer-vagrant-al2bx.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer-vagrant-al2bx.pkr.hcl

      - name: Build Vagrant Box
        run: packer build packer-vagrant-al2bx.pkr.hcl

      - name: List contents of the output directory
        run: |
          echo "Listing contents of /amazonlnux-2box/"
          ls -l /amazonlnux-2box/

      - name: Upload Box Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vagrant-box
          path: amazonlnux-2box/al2chef.box
          retention-days: 30  # Increased retention period
